name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Build
      run: npm ci && npm run build
    - name: Deploy to Server
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: './out/'
        remote: '~/'
        host: ${{secrets.SSH_HOST}}
        user: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_SECRET_KEY}}