name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@master
      - name: Build the site static assets
        run: npm ci && npm run build
      - name: ssh and deploy
        uses: Techie-Pi/node-vps-deployment@main
        with:
          remote-path: "~/deployment/staging"
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          source: "./out/*"
          target: "/var/www/html"
